### ISSUE TITLE
debounce with cancel??

### ISSUE THREAD

**Issue by PatrickJS** [bendrucker/next-tick-debounce#1]
can has cancel?

**Comment by bendrucker** [comment]
The underlying APIs (specifically `process.nextTick` in Node) don't support this so for now the answer is no. You could create a mechanism to return early in the callback but I'll leave that for another package.

**Comment by PatrickJS** [comment]
ya, I ended up just creating my own debounce that cancels

**Comment by bendrucker** [comment]
👍  Once you're doing that there's no advantage in doing it here
